### ISSUE TITLE
driver_installer.exe missing? 

### ISSUE THREAD

**Issue by jochot** [fpv-wtf/driver-installer#1]
Hey! 
I might be too stupid for this, but if I download it as a ZIP I cannot find any driver_installer.exe, there's a manifest, a .c and .rc, but no .exe? 
Also in this Git I can't find any, am I missing something over here that is obvious?

**Comment by stylesuxx** [comment]
In the releases, first file: https://github.com/fpv-wtf/driver-installer/releases/tag/v1.0.0

**Comment by jochot** [comment]
Indeed, thanks and sorry!
